/**
 * Builder configuration, parsed and validated once at startup.
 *
 * Two modes:
 *
 *   local  reads a tarball from disk, writes artifacts to a directory.
 *          The M1 development loop; no AWS involved.
 *
 *   aws    downloads from a presigned URL, uploads to S3, reports progress to
 *          the control plane. What Fargate actually runs.
 *
 * A discriminated union rather than a bag of optionals, so a field that only
 * exists in one mode cannot be read in the other without the compiler noticing.
 *
 * Deliberately hand-rolled rather than using Zod: every dependency here ends up
 * inside the container that runs untrusted code. Zod lives in the API, where
 * request bodies are attacker-controlled and genuinely complex.
 */

import { BuildError } from './errors.js';
import { generateDeploymentId } from './ids.js';

export type BuilderMode = 'local' | 'aws';

interface CommonConfig {
  deploymentId: string;
  /** Scratch space. Emptied on start; must be writable. */
  workDir: string;

  buildTimeoutSec: number;
  /** Compressed archive cap, checked before anything is unpacked. */
  maxArchiveBytes: number;
  /** Uncompressed cap, enforced while unpacking (zip-bomb defence). */
  maxSourceBytes: number;
  maxSourceFiles: number;
  maxArtifactBytes: number;
  maxArtifactFiles: number;
  maxLogBytes: number;
  logLevel: 'debug' | 'info' | 'warn' | 'error';

  /** Values scrubbed from every log line before it is written. */
  secrets: string[];
}

export interface LocalConfig extends CommonConfig {
  mode: 'local';
  sourcePath: string;
  outputDir: string;
}

export interface AwsConfig extends CommonConfig {
  mode: 'aws';
  /** Presigned GET, short-lived, for one object. Never a GitHub URL (ADR-0004). */
  sourceUrl: string;
  artifactBucket: string;
  /** Server-generated. Never influenced by the repository being built. */
  artifactPrefix: string;
  /** Where progress is reported. The container has no DynamoDB access (ADR-0009). */
  statusUrl: string;
  statusToken: string;
}

export type BuilderConfig = LocalConfig | AwsConfig;

const MB = 1024 * 1024;

export const DEFAULTS = {
  buildTimeoutSec: 600,
  maxArchiveBytes: 100 * MB,
  maxSourceBytes: 500 * MB,
  maxSourceFiles: 20_000,
  maxArtifactBytes: 500 * MB,
  maxArtifactFiles: 20_000,
  maxLogBytes: 10 * MB,
} as const;

export interface ConfigOverrides {
  sourcePath?: string;
  outputDir?: string;
}

export function loadConfig(
  env: NodeJS.ProcessEnv = process.env,
  overrides: ConfigOverrides = {},
): BuilderConfig {
  const mode = (env['BUILDER_MODE'] ?? 'local').trim();
  if (mode !== 'local' && mode !== 'aws') {
    throw new BuildError('CONFIG_ERROR', `BUILDER_MODE must be "local" or "aws", got "${mode}"`);
  }

  const common: CommonConfig = {
    deploymentId: str(env, 'DEPLOYMENT_ID') ?? generateDeploymentId(),
    workDir: str(env, 'WORK_DIR') ?? '/workspace',
    buildTimeoutSec: int(env, 'BUILD_TIMEOUT_SEC', DEFAULTS.buildTimeoutSec, 1, 3600),
    maxArchiveBytes: int(env, 'MAX_ARCHIVE_BYTES', DEFAULTS.maxArchiveBytes, 1024, 5_000 * MB),
    maxSourceBytes: int(env, 'MAX_SOURCE_BYTES', DEFAULTS.maxSourceBytes, 1024, 5_000 * MB),
    maxSourceFiles: int(env, 'MAX_SOURCE_FILES', DEFAULTS.maxSourceFiles, 1, 1_000_000),
    maxArtifactBytes: int(env, 'MAX_ARTIFACT_BYTES', DEFAULTS.maxArtifactBytes, 1024, 5_000 * MB),
    maxArtifactFiles: int(env, 'MAX_ARTIFACT_FILES', DEFAULTS.maxArtifactFiles, 1, 1_000_000),
    maxLogBytes: int(env, 'MAX_LOG_BYTES', DEFAULTS.maxLogBytes, 1024, 1_000 * MB),
    logLevel: level(env, 'LOG_LEVEL'),
    secrets: [],
  };

  if (mode === 'local') {
    const sourcePath = overrides.sourcePath ?? str(env, 'SOURCE_PATH');
    if (!sourcePath) {
      throw new BuildError(
        'CONFIG_ERROR',
        'no source tarball given. Pass a path as an argument, or set SOURCE_PATH.',
      );
    }

    const outputDir = overrides.outputDir ?? str(env, 'OUTPUT_DIR');
    if (!outputDir) throw new BuildError('CONFIG_ERROR', 'OUTPUT_DIR is required in local mode.');

    return { ...common, mode: 'local', sourcePath, outputDir };
  }

  const sourceUrl = require_(env, 'SOURCE_URL');
  const statusToken = require_(env, 'STATUS_TOKEN');
  const artifactPrefix = require_(env, 'ARTIFACT_PREFIX');

  if (!/^https:\/\//i.test(sourceUrl)) {
    throw new BuildError('CONFIG_ERROR', 'SOURCE_URL must be an https URL');
  }
  // The prefix becomes an S3 key and an IAM resource pattern. It is generated by
  // the control plane, but assert its shape anyway: a leading slash or a "@..@"
  // segment here would be a serious bug elsewhere, and this is where it shows.
  if (artifactPrefix.startsWith('/') || artifactPrefix.includes('..')) {
    throw new BuildError('CONFIG_ERROR', 'ARTIFACT_PREFIX must be a relative path without ".."');
  }

  return {
    ...common,
    mode: 'aws',
    sourceUrl,
    artifactBucket: require_(env, 'ARTIFACT_BUCKET'),
    artifactPrefix: artifactPrefix.replace(/\/+$/, ''),
    statusUrl: require_(env, 'STATUS_URL'),
    statusToken,
    // Both are credentials in their own right: the token authorises status
    // writes, the URL grants read access to the source archive.
    secrets: [statusToken, sourceUrl],
  };
}

function str(env: NodeJS.ProcessEnv, key: string): string | undefined {
  const raw = env[key];
  if (raw === undefined) return undefined;
  const trimmed = raw.trim();
  return trimmed.length > 0 ? trimmed : undefined;
}

function require_(env: NodeJS.ProcessEnv, key: string): string {
  const value = str(env, key);
  if (!value) throw new BuildError('CONFIG_ERROR', `${key} is required in aws mode`);
  return value;
}

function int(
  env: NodeJS.ProcessEnv,
  key: string,
  fallback: number,
  min: number,
  max: number,
): number {
  const raw = str(env, key);
  if (raw === undefined) return fallback;

  const parsed = Number(raw);
  if (!Number.isInteger(parsed)) {
    throw new BuildError('CONFIG_ERROR', `${key} must be a whole number, got "${raw}"`);
  }
  if (parsed < min || parsed > max) {
    throw new BuildError('CONFIG_ERROR', `${key} must be between ${min} and ${max}, got ${parsed}`);
  }
  return parsed;
}

function level(env: NodeJS.ProcessEnv, key: string): CommonConfig['logLevel'] {
  const raw = (str(env, key) ?? 'info').toLowerCase();
  if (raw === 'debug' || raw === 'info' || raw === 'warn' || raw === 'error') return raw;
  throw new BuildError('CONFIG_ERROR', `${key} must be debug|info|warn|error, got "${raw}"`);
}

/** Config as loggable fields. Never includes anything from `secrets`. */
export function describeConfig(c: BuilderConfig): Record<string, unknown> {
  const common = {
    mode: c.mode,
    workDir: c.workDir,
    buildTimeoutSec: c.buildTimeoutSec,
    maxArtifactBytes: c.maxArtifactBytes,
    maxArtifactFiles: c.maxArtifactFiles,
  };

  return c.mode === 'local'
    ? { ...common, sourcePath: c.sourcePath, outputDir: c.outputDir }
    : { ...common, artifactBucket: c.artifactBucket, artifactPrefix: c.artifactPrefix };
}
